# Generated by Django 3.2.23 on 2024-01-21 08:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Background Image')),
                ('logo_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Logo Image')),
            ],
        ),
    ]
