# Generated by Django 3.2.23 on 2024-01-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_myimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImage',
        ),
    ]
